[package]
name = "rpcl2-derive"
description = "Derive macros for the ros_pointcloud2 crate."
version = "1.0.0-rc.3"
edition = "2021"
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["ros", "pointcloud2", "ros_pointcloud2"]
categories = [
    "science::robotics",
    "encoding",
    "data-structures",
    "api-bindings",
]
rust-version = "1.85.1"

[lib]
proc-macro = true

[dependencies]
syn = "3.0"
quote = "1.0"
proc-macro2 = "1.0"
