# syntax=docker/dockerfile:1
FROM ros:rolling

# Update default packages
RUN apt-get update

# Get Ubuntu packages
RUN apt-get install -y \
    build-essential \
    curl \
    libclang-dev \
    git \
    python3-pip \
    python3-vcstool \
    ros-rolling-test-msgs ros-rolling-example-interfaces

# Get Rust
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

# colcon tooling
RUN pip install --break-system-packages colcon-cargo-ros2 # is a fork but easier

WORKDIR /ros2_rust_ws
WORKDIR /ros2_rust_ws/src/ros_pointcloud2
COPY . .

# Modify Cargo.toml to include the ros node
RUN awk 'BEGIN{added=0} /members[[:space:]]*=[[:space:]]*\[/{print; while(getline){ if($0 ~ /\]/ && added==0){ print "    \"integration/rclrs_tests\","; added=1; print; break } print} next} {print}' Cargo.toml > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml

WORKDIR /ros2_rust_ws

RUN chmod +x /ros2_rust_ws/src/ros_pointcloud2/integration/tests/rclrs_test.bash
ENTRYPOINT [ "/ros2_rust_ws/src/ros_pointcloud2/integration/tests/rclrs_test.bash" ]
