# syntax=docker/dockerfile:1
FROM ros:humble

# Update default packages
RUN apt-get update

# Get Ubuntu packages
RUN apt-get install -y \
    build-essential \
    curl \
    libclang-dev \
    git \
    python3-pip \
    python3-vcstool

# Get ros test messages
RUN apt-get install -y ros-humble-test-msgs ros-humble-example-interfaces

# Get Rust
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
RUN cargo install --debug cargo-ament-build
RUN pip install git+https://github.com/colcon/colcon-cargo.git
RUN pip install git+https://github.com/colcon/colcon-ros-cargo.git

WORKDIR /ros2_rust_build
RUN git clone https://github.com/ros2-rust/ros2_rust.git src/ros2_rust
RUN vcs import src < src/ros2_rust/ros2_rust_humble.repos
RUN . /opt/ros/humble/setup.sh && colcon build

WORKDIR /rclrs
COPY . .
RUN chmod +x /rclrs/tests/rclrs_test.bash
ENTRYPOINT [ "/rclrs/tests/rclrs_test.bash" ]
